"""reconcile_prod_schema_to_head

Revision ID: 02fb62787b57
Revises: e1b3c5d7f9a2
Create Date: 2026-08-05 10:54:23.459500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02fb62787b57'
down_revision: Union[str, None] = 'e1b3c5d7f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_family_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('subfamily_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('postscript_name', sa.String(), nullable=True),
    sa.Column('weight_class', sa.Integer(), nullable=True),
    sa.Column('width_class', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_font_uploads_normalized_family_name'), 'font_uploads', ['normalized_family_name'], unique=False)
    op.create_table('ollamapullstatus',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('admin_slot', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_slot')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('access_tokens',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_access_tokens_token'), 'access_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False)
    op.create_table('async_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_tasks_owner_id'), 'async_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_async_tasks_status'), 'async_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_async_tasks_type'), 'async_tasks', ['type'], unique=False)
    op.create_table('template_create_infos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('fonts', sa.JSON(), nullable=True),
    sa.Column('pptx_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slide_htmls', sa.JSON(), nullable=False),
    sa.Column('slide_image_urls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_create_infos_owner_id'), 'template_create_infos', ['owner_id'], unique=False)
    op.create_table('template_v2',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_layouts', sa.JSON(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('merged_components', sa.JSON(), nullable=True),
    sa.Column('layouts', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_v2_owner_id'), 'template_v2', ['owner_id'], unique=False)
    op.create_table('chat_history_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('presentation_id', sa.Uuid(), nullable=True),
    sa.Column('template_v2_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_v2_id'], ['template_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_messages_conversation_id'), 'chat_history_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_owner_id'), 'chat_history_messages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_position'), 'chat_history_messages', ['position'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_presentation_id'), 'chat_history_messages', ['presentation_id'], unique=False)
    op.create_index(op.f('ix_chat_history_messages_template_v2_id'), 'chat_history_messages', ['template_v2_id'], unique=False)
    op.add_column('async_presentation_generation_tasks', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_async_presentation_generation_tasks_owner_id'), 'async_presentation_generation_tasks', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'async_presentation_generation_tasks', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('imageasset', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_imageasset_owner_id'), 'imageasset', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'imageasset', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('presentation_layout_codes', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_presentation_layout_codes_owner_id'), 'presentation_layout_codes', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'presentation_layout_codes', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('presentations', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('presentations', sa.Column('version', sa.Enum('v1-standard', 'v2-standard', name='presentation_version', native_enum=False, create_constraint=True), nullable=False, server_default='v1-standard'))
    op.add_column('presentations', sa.Column('theme', sa.JSON(), nullable=True))
    op.add_column('presentations', sa.Column('fonts', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_presentations_owner_id'), 'presentations', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'presentations', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('slides', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('slides', sa.Column('ui', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_slides_owner_id'), 'slides', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'slides', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('templates', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_templates_owner_id'), 'templates', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'templates', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('webhook_subscriptions', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_webhook_subscriptions_owner_id'), 'webhook_subscriptions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'webhook_subscriptions', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_webhook_subscriptions_owner_id'), table_name='webhook_subscriptions')
    op.drop_column('webhook_subscriptions', 'owner_id')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_index(op.f('ix_templates_owner_id'), table_name='templates')
    op.drop_column('templates', 'owner_id')
    op.drop_constraint(None, 'slides', type_='foreignkey')
    op.drop_index(op.f('ix_slides_owner_id'), table_name='slides')
    op.drop_column('slides', 'ui')
    op.drop_column('slides', 'owner_id')
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    op.drop_index(op.f('ix_presentations_owner_id'), table_name='presentations')
    op.drop_column('presentations', 'fonts')
    op.drop_column('presentations', 'theme')
    op.drop_column('presentations', 'version')
    op.drop_column('presentations', 'owner_id')
    op.drop_constraint(None, 'presentation_layout_codes', type_='foreignkey')
    op.drop_index(op.f('ix_presentation_layout_codes_owner_id'), table_name='presentation_layout_codes')
    op.drop_column('presentation_layout_codes', 'owner_id')
    op.drop_constraint(None, 'imageasset', type_='foreignkey')
    op.drop_index(op.f('ix_imageasset_owner_id'), table_name='imageasset')
    op.drop_column('imageasset', 'owner_id')
    op.drop_constraint(None, 'async_presentation_generation_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_async_presentation_generation_tasks_owner_id'), table_name='async_presentation_generation_tasks')
    op.drop_column('async_presentation_generation_tasks', 'owner_id')
    op.drop_index(op.f('ix_chat_history_messages_template_v2_id'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_presentation_id'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_position'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_owner_id'), table_name='chat_history_messages')
    op.drop_index(op.f('ix_chat_history_messages_conversation_id'), table_name='chat_history_messages')
    op.drop_table('chat_history_messages')
    op.drop_index(op.f('ix_template_v2_owner_id'), table_name='template_v2')
    op.drop_table('template_v2')
    op.drop_index(op.f('ix_template_create_infos_owner_id'), table_name='template_create_infos')
    op.drop_table('template_create_infos')
    op.drop_index(op.f('ix_async_tasks_type'), table_name='async_tasks')
    op.drop_index(op.f('ix_async_tasks_status'), table_name='async_tasks')
    op.drop_index(op.f('ix_async_tasks_owner_id'), table_name='async_tasks')
    op.drop_table('async_tasks')
    op.drop_index(op.f('ix_access_tokens_user_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_token'), table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('provider_settings')
    op.drop_table('ollamapullstatus')
    op.drop_index(op.f('ix_font_uploads_normalized_family_name'), table_name='font_uploads')
    op.drop_table('font_uploads')
    # ### end Alembic commands ###
